language: php
php:
  - 5.6
  - 7.0
  - nightly

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-stable --prefer-lowest --no-interaction

script: composer test
