language: php

sudo: false

before_script:
  - travis_retry composer self-update
  - travis_retry composer require "illuminate/support:${ILLUMINATE_VERSION}"

script:
  - phpunit

matrix:
  include:
    - php: 7.1
      env: ILLUMINATE_VERSION=5.8.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.8.*
